### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by cassioalmeidas** [Tachionstrahl/SignLanguageRecognition#8]
I'm using ubuntu 18.04 and can build it smoothly, however, when I run ./run_prediction.sh it shows in the caption only "Buffer: X", where X is a number. The terminal shows the error:

 ``Coordinates size not equal 86. Actual size: 128``

screenshot attached.

![Captura de tela de 2020-12-03 20-34-29](https://user-images.githubusercontent.com/104586/101102861-cf614100-35a7-11eb-9115-37021d40e81d.png)

**Comment by Tachionstrahl** [comment]
Hi @cassioalmeidas,

thanks for submitting your request. Please ignore the message, we don't really know why, but sometimes MediaPipe's HandTracking detects 3 hands and delivers too much coordinates. 
To trigger the prediction of your signed word, just put your hands out of the picture for a few seconds. Instead of the Buffer-Counter, you should now see the predicted word.
